import "server-only";
import crypto from "crypto";
import { adminClient } from "@/lib/supabase";
import { AAROHI_SOURCE_TYPES,AAROHI_CHANNELS,clampScore,derivePriorityBand } from "@/lib/aarohi/contracts";
import type { QfjAarohiProjectionRequest,QfjAarohiOperation } from "@/lib/jarvis/aarohiProjectionContract";
const text=(v:unknown,n=300)=>typeof v==="string"?v.trim().replace(/\s+/g," ").slice(0,n):"";
const bool=(v:unknown)=>typeof v==="boolean"?v:null;
const forbiddenEventKey=/(message|body|content|text|transcript|secret|token|password|phone|email|address)/i;
function deterministicUuid(key:string){const b=crypto.createHash("sha256").update(`qf-aarohi:${key}`).digest().subarray(0,16);b[6]=(b[6]&0x0f)|0x40;b[8]=(b[8]&0x3f)|0x80;const h=b.toString("hex");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;}
function safeData(v:unknown){if(!v||typeof v!=="object"||Array.isArray(v))return {};const o:Record<string,unknown>={};for(const [k,x] of Object.entries(v as Record<string,unknown>).slice(0,30)){if(forbiddenEventKey.test(k))continue;if(typeof x==="string")o[k]=x.slice(0,180);else if(typeof x==="number"||typeof x==="boolean"||x===null)o[k]=x;else if(Array.isArray(x))o[k]=x.filter(y=>typeof y==="string"||typeof y==="number"||typeof y==="boolean").slice(0,20);}return o;}
async function existsProspect(id:string){const r=await adminClient().from("aarohi_prospects").select("id,ai_paused,human_takeover,do_not_contact").eq("id",id).eq("tenant_id","quickfurno").maybeSingle();if(r.error)throw r.error;return r.data;}
async function eventMarker(operationId:string,prospectId:string|null,eventType:string,summary:string,refType?:string,refId?:string,eventData:unknown={}){const r=await adminClient().from("aarohi_events").upsert({id:deterministicUuid(`event:${operationId}`),tenant_id:"quickfurno",prospect_id:prospectId,event_type:eventType,actor_type:"JARVIS",actor_reference:"aarohi-projection",safe_summary:summary.slice(0,500),reference_type:refType??null,reference_id:refId??null,idempotency_key:`jarvis.op.${operationId}`,event_data:safeData(eventData)},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;return r.data.id;}
async function applyOne(op:QfjAarohiOperation){const db=adminClient();const marker=await db.from("aarohi_events").select("id,reference_id").eq("tenant_id","quickfurno").eq("idempotency_key",`jarvis.op.${op.operationId}`).maybeSingle();if(marker.error)throw marker.error;if(marker.data)return {operationId:op.operationId,status:"REPLAY",referenceId:marker.data.reference_id??null};const p=op.payload;
 if(op.kind==="DISCOVER_PROSPECT"){if(op.prospectId)throw new Error("discover_has_prospect_id");const business=text(p.businessName,160),slug=text(p.citySlug,80);if(!business||!slug)throw new Error("invalid_discovery");const city=await db.from("cities").select("id,name,slug").eq("slug",slug).eq("is_active",true).maybeSingle();if(city.error)throw city.error;if(!city.data)throw new Error("inactive_market");const id=deterministicUuid(`prospect:${op.operationId}`);const normalized=business.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();const r=await db.from("aarohi_prospects").upsert({id,tenant_id:"quickfurno",city_id:city.data.id,business_name:business,normalized_business_name:normalized,primary_category:text(p.primaryCategory,120)||null,area:text(p.area,120)||null,pincode:text(p.pincode,10)||null,state:text(p.state,80)||null,website:text(p.website,300)||null,primary_phone:text(p.primaryPhone,30)||null,whatsapp_available:bool(p.whatsappAvailable),email:text(p.email,180)||null,contact_person_name:text(p.contactPersonName,120)||null,contact_person_role:text(p.contactPersonRole,120)||null,source_confidence:clampScore(p.sourceConfidence),data_confidence:clampScore(p.dataConfidence)},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;await eventMarker(op.operationId,id,"prospect.discovered","Prospect discovered by Aarohi/Jarvis","prospect",id,{city:city.data.slug});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(!op.prospectId)throw new Error("prospect_id_required");const prospect=await existsProspect(op.prospectId);if(!prospect)throw new Error("prospect_not_found");
 if(op.kind==="SOURCE_OBSERVED"){const sourceType=text(p.sourceType,30);if(!AAROHI_SOURCE_TYPES.includes(sourceType as never))throw new Error("invalid_source");const id=deterministicUuid(`source:${op.operationId}`);const r=await db.from("aarohi_prospect_sources").upsert({id,prospect_id:op.prospectId,source_type:sourceType,source_name:text(p.sourceName,120)||null,source_url:text(p.sourceUrl,500)||null,discovery_query:text(p.discoveryQuery,300)||null,discovery_batch_id:text(p.discoveryBatchId,120)||null,raw_business_name:text(p.rawBusinessName,200)||null,raw_phone:text(p.rawPhone,40)||null,raw_email:text(p.rawEmail,180)||null,raw_address:text(p.rawAddress,500)||null,raw_category:text(p.rawCategory,160)||null,observed_at:text(p.observedAt,40)||null,confidence:clampScore(p.confidence)},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;await eventMarker(op.operationId,op.prospectId,"prospect.enriched",`${sourceType} source observed`,"source",id,{source_type:sourceType});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(op.kind==="CHANNEL_OBSERVED"){const channel=text(p.channel,30);if(!AAROHI_CHANNELS.includes(channel as never)||channel==="SYSTEM")throw new Error("invalid_channel");const ext=text(p.externalReference,300);if(!ext)throw new Error("external_reference_required");const id=deterministicUuid(`channel:${op.operationId}`);const r=await db.from("aarohi_channel_identities").upsert({id,prospect_id:op.prospectId,channel,external_reference:ext,profile_url:text(p.profileUrl,500)||null,display_name:text(p.displayName,200)||null,verification_status:"OBSERVED"},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;await eventMarker(op.operationId,op.prospectId,"prospect.enriched",`${channel} identity observed`,"channel_identity",id,{channel});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(op.kind==="CONVERSATION_PROJECT"){const channel=text(p.channel,30);if(!["CALL","WHATSAPP","INSTAGRAM","FACEBOOK","LINKEDIN","X"].includes(channel))throw new Error("invalid_conversation_channel");const ref=text(p.orchestrationReference,200);if(!ref)throw new Error("orchestration_reference_required");let q=await db.from("aarohi_conversations").select("id").eq("prospect_id",op.prospectId).eq("orchestration_reference",ref).maybeSingle();if(q.error)throw q.error;const id=q.data?.id??deterministicUuid(`conversation:${op.operationId}`);const state=prospect.human_takeover?"HUMAN":prospect.ai_paused?"PAUSED":"OPEN";const r=await db.from("aarohi_conversations").upsert({id,prospect_id:op.prospectId,channel,external_thread_reference:text(p.externalThreadReference,300)||null,state,current_intent:text(p.currentIntent,160)||null,current_objection:text(p.currentObjection,240)||null,last_commitment:text(p.lastCommitment,240)||null,next_action:text(p.nextAction,240)||null,follow_up_at:text(p.followUpAt,40)||null,summary:text(p.summary,800)||null,orchestration_reference:ref,updated_at:new Date().toISOString()},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;await eventMarker(op.operationId,op.prospectId,"conversation.started",`${channel} conversation projection updated`,"conversation",id,{channel,state});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(op.kind==="TASK_PROJECT"){const ref=text(p.workflowReference,200);if(!ref)throw new Error("workflow_reference_required");const taskType=text(p.taskType,40);if(!["CALL","FOLLOW_UP","WHATSAPP","REVIEW","IDENTITY_REVIEW","REGISTRATION_ASSIST","PAYMENT_FOLLOWUP","HUMAN_CALLBACK","OTHER"].includes(taskType))throw new Error("invalid_task_type");let q=await db.from("aarohi_tasks").select("id").eq("prospect_id",op.prospectId).eq("workflow_reference",ref).maybeSingle();if(q.error)throw q.error;const id=q.data?.id??deterministicUuid(`task:${op.operationId}`);const status=text(p.status,20)||"OPEN";if(!["OPEN","IN_PROGRESS","DONE","CANCELLED","BLOCKED"].includes(status))throw new Error("invalid_task_status");const r=await db.from("aarohi_tasks").upsert({id,prospect_id:op.prospectId,task_type:taskType,due_at:text(p.dueAt,40)||null,priority:["LOW","NORMAL","HIGH","URGENT"].includes(text(p.priority,20))?text(p.priority,20):"NORMAL",reason:text(p.reason,500)||null,status:prospect.do_not_contact&&["CALL","FOLLOW_UP","WHATSAPP"].includes(taskType)?"CANCELLED":status,workflow_reference:ref,updated_at:new Date().toISOString()},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;await eventMarker(op.operationId,op.prospectId,"task.updated",`${taskType} task projection updated`,"task",id,{status:r.data?status:"OPEN"});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(op.kind==="SCORE_PROJECT"){const values={qualification:clampScore(p.qualificationScore),contactability:clampScore(p.contactabilityScore),engagement:clampScore(p.engagementScore),commercialIntent:clampScore(p.commercialIntentScore),dataConfidence:clampScore(p.dataConfidenceScore)};const priority=derivePriorityBand(values);const id=deterministicUuid(`score:${op.operationId}`);const reasonCodes=Array.isArray(p.reasonCodes)?p.reasonCodes.filter(x=>typeof x==="string").map(x=>String(x).slice(0,60)).slice(0,20):[];const r=await db.from("aarohi_scores").upsert({id,prospect_id:op.prospectId,qualification_score:values.qualification,contactability_score:values.contactability,engagement_score:values.engagement,commercial_intent_score:values.commercialIntent,data_confidence_score:values.dataConfidence,priority_band:priority,score_version:text(p.scoreVersion,60)||"aarohi-jarvis-v1",score_reason_codes:reasonCodes,calculated_by:"JARVIS"},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;const u=await db.from("aarohi_prospects").update({priority_band:priority,data_confidence:values.dataConfidence,updated_at:new Date().toISOString()}).eq("id",op.prospectId);if(u.error)throw u.error;await eventMarker(op.operationId,op.prospectId,"prospect.qualified",`Structured scoring updated; priority ${priority}`,"score",id,{reason_codes:reasonCodes});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(op.kind==="IDENTITY_MATCH_RECOMMENDED"){const other=text(p.otherProspectId,40);const score=clampScore(p.matchScore);if(!other||other===op.prospectId||!(await existsProspect(other)))throw new Error("invalid_identity_candidate");const [a,b]=[op.prospectId,other].sort();const id=deterministicUuid(`identity:${a}:${b}`);const r=await db.from("aarohi_identity_matches").upsert({id,prospect_a_id:a,prospect_b_id:b,match_score:score,phone_match:bool(p.phoneMatch)??false,domain_match:bool(p.domainMatch)??false,name_match:bool(p.nameMatch)??false,address_match:bool(p.addressMatch)??false,social_match:bool(p.socialMatch)??false,evidence:safeData(p.evidence),status:"RECOMMENDED"},{onConflict:"id"}).select("id").single();if(r.error)throw r.error;await eventMarker(op.operationId,op.prospectId,"identity.match_recommended",`Possible duplicate recommended at ${score}% confidence`,"identity_match",id,{match_score:score});return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 if(op.kind==="EVENT_APPEND"){const eventType=text(p.eventType,100);if(!/^(prospect|outreach|call|conversation|objection|intent|whatsapp|registration|package|payment|vendor|aarohi|human|task)\.[a-z0-9_.-]{1,80}$/i.test(eventType))throw new Error("invalid_event_type");const summary=text(p.safeSummary,500);const id=await eventMarker(op.operationId,op.prospectId,eventType,summary||"Structured Aarohi event",text(p.referenceType,80)||undefined,text(p.referenceId,160)||undefined,p.eventData);return {operationId:op.operationId,status:"APPLIED",referenceId:id};}
 throw new Error("unsupported_operation");
}
export async function applyJarvisAarohiProjection(request:QfjAarohiProjectionRequest){const results=[] as Array<{operationId:string;status:string;referenceId:string|null}>;for(const op of request.operations){try{results.push(await applyOne(op));}catch(error){results.push({operationId:op.operationId,status:`REFUSED:${error instanceof Error?error.message:"unknown"}`,referenceId:null});}}return {requestId:request.requestId,results};}
