import Link from "next/link";
import { createProspectAction } from "../actions";
import { AarohiBadge,AarohiPageHead,ProspectLink,formatWhen } from "@/components/admin/aarohi/AarohiPrimitives";
import { listAarohiProspects,listActiveAarohiCities } from "@/services/aarohiCrmService";
export const dynamic="force-dynamic";
const one=(sp:Record<string,string|string[]|undefined>|undefined,k:string)=>{const v=sp?.[k];return Array.isArray(v)?v[0]:v};
export default async function ProspectsPage(props:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
 // Next 16: searchParams is a Promise. Read synchronously it type-checks, builds clean, then returns undefined at runtime.
 const searchParams=await props.searchParams;
 const query={page:one(searchParams,"page"),search:one(searchParams,"search"),stage:one(searchParams,"stage"),priority:one(searchParams,"priority"),area:one(searchParams,"area"),whatsapp_available:one(searchParams,"whatsapp_available"),human_takeover:one(searchParams,"human_takeover"),do_not_contact:one(searchParams,"do_not_contact")}; const [data,cities]=await Promise.all([listAarohiProspects(query),listActiveAarohiCities()]);
 return <><AarohiPageHead title="Prospects" description="Discovered businesses stay here until Core confirms an active vendor. Nothing on this page creates a vendor record." action={<details><summary className="qf-aarohi-btn" data-tone="primary">Add prospect</summary><form action={createProspectAction} className="qf-aarohi-panel" style={{position:"absolute",right:28,zIndex:10,width:420,marginTop:8}}><div className="qf-aarohi-formgrid"><label>Business<input className="qf-aarohi-input" name="business_name" required/></label><label>Active city<select className="qf-aarohi-select" name="city_id" required>{cities.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Category<input className="qf-aarohi-input" name="primary_category"/></label><label>Area<input className="qf-aarohi-input" name="area"/></label><label>Phone<input className="qf-aarohi-input" name="primary_phone"/></label><label>Website<input className="qf-aarohi-input" name="website"/></label><label className="wide">Contact person<input className="qf-aarohi-input" name="contact_person_name"/></label></div><button className="qf-aarohi-btn" data-tone="primary" style={{marginTop:10}}>Create prospect</button></form></details>}/>
 <form className="qf-aarohi-filters"><input className="qf-aarohi-input" name="search" defaultValue={query.search as string} placeholder="Business, phone, contact, area, website…"/><select className="qf-aarohi-select" name="stage" defaultValue={query.stage as string}><option value="">All stages</option>{["DISCOVERED","ENRICHED","QUALIFIED","OUTREACH_READY","CONTACTED","ENGAGED","INTERESTED","CONVERSION","WON","LOST","SUPPRESSED"].map(x=><option key={x}>{x}</option>)}</select><select className="qf-aarohi-select" name="priority" defaultValue={query.priority as string}><option value="">Priority</option>{["A+","A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select><input className="qf-aarohi-input" name="area" defaultValue={query.area as string} placeholder="Area"/><label><input type="checkbox" name="whatsapp_available" value="true" defaultChecked={query.whatsapp_available==="true"}/> WhatsApp</label><label><input type="checkbox" name="human_takeover" value="true" defaultChecked={query.human_takeover==="true"}/> Human</label><label><input type="checkbox" name="do_not_contact" value="true" defaultChecked={query.do_not_contact==="true"}/> Suppressed</label><button className="qf-aarohi-btn">Filter</button><Link className="qf-aarohi-btn" data-tone="ghost" href="/admin/aarohi/prospects">Reset</Link></form>
 <div className="qf-aarohi-table-wrap"><table className="qf-aarohi-table"><thead><tr><th>Business</th><th>Category</th><th>Area</th><th>Phone</th><th>WhatsApp</th><th>Stage</th><th>Priority</th><th>Last activity</th><th>Next action</th><th>Owner</th></tr></thead><tbody>{data.rows.map((r:any)=><tr key={r.id}><td><ProspectLink id={r.id}>{r.business_name}</ProspectLink>{r.do_not_contact?<div><AarohiBadge tone="hot">DO NOT CONTACT</AarohiBadge></div>:null}</td><td>{r.primary_category||"—"}</td><td>{r.area||r.cities?.name||"—"}</td><td>{r.primary_phone||"—"}</td><td>{r.whatsapp_available?"✓":"—"}</td><td><AarohiBadge tone={r.prospect_stage==="INTERESTED"?"hot":r.prospect_stage==="WON"?"good":"neutral"}>{r.prospect_stage}</AarohiBadge></td><td><AarohiBadge tone={r.priority_band==="A+"?"hot":"neutral"}>{r.priority_band}</AarohiBadge></td><td>{formatWhen(r.last_activity_at)}</td><td>{r.next_action_type||"—"}<small>{r.next_action_at?` · ${formatWhen(r.next_action_at)}`:""}</small></td><td>{r.human_takeover?"HUMAN":r.agent_owner}</td></tr>)}</tbody></table></div><p className="qf-aarohi-note">Showing {data.rows.length} of {data.total} prospects · page {data.page}. Bulk communication is intentionally unavailable.</p></>;
}
