import Link from "next/link";
import { notFound } from "next/navigation";
import { AarohiBadge,AarohiPageHead,formatWhen } from "@/components/admin/aarohi/AarohiPrimitives";
import { getAarohiProspect,listActivePackages } from "@/services/aarohiCrmService";
import { createTaskAction,completeHandoffAction,identityDecisionAction,pauseAarohiAction,scoreProspectAction,selectPackageAction,suppressProspectAction,takeoverProspectAction,updateWorkflowAction } from "../../actions";
export const dynamic="force-dynamic";
function Field({label,value}:{label:string;value:React.ReactNode}){return <><dt>{label}</dt><dd>{value||"—"}</dd></>}
export default async function Prospect360Page({params}:{params:{id:string}}){const [data,packages]=await Promise.all([getAarohiProspect(params.id),listActivePackages()]);if(!data)notFound();const p:any=data.prospect;const score:any=data.scores[0]??{};const handoff:any=data.handoff;const core:any=data.core;return <>
 <AarohiPageHead eyebrow="Prospect 360" title={p.business_name} description={`${p.primary_category||"Uncategorised"} · ${p.area||p.cities?.name||""} · ${p.cities?.name||"Active market"}`} action={<div className="qf-aarohi-actions"><AarohiBadge tone={p.priority_band==="A+"?"hot":"neutral"}>{p.priority_band}</AarohiBadge><AarohiBadge tone={p.prospect_stage==="INTERESTED"?"hot":p.prospect_stage==="WON"?"good":"neutral"}>{p.prospect_stage}</AarohiBadge>{p.do_not_contact?<AarohiBadge tone="hot">DO NOT CONTACT</AarohiBadge>:null}</div>}/>
 <div className="qf-aarohi-360">
  <aside className="qf-aarohi-panel"><div className="qf-aarohi-panel-head"><div><h2>Business profile</h2><p>Prospect identity, not a vendor record.</p></div></div><dl className="qf-aarohi-profile-list"><Field label="Business" value={p.business_name}/><Field label="Category" value={p.primary_category}/><Field label="Subcategories" value={(p.subcategories||[]).join(", ")}/><Field label="Address" value={p.address}/><Field label="Area" value={p.area}/><Field label="Pincode" value={p.pincode}/><Field label="City" value={p.cities?.name}/><Field label="Phone" value={p.primary_phone}/><Field label="WhatsApp" value={p.whatsapp_available?"Available":"Not confirmed"}/><Field label="Email" value={p.email}/><Field label="Website" value={p.website?<a href={p.website} target="_blank" rel="noreferrer">Open ↗</a>:null}/><Field label="Google" value={p.google_profile_url?<a href={p.google_profile_url} target="_blank" rel="noreferrer">Profile ↗</a>:null}/><Field label="Instagram" value={p.instagram_url}/><Field label="Facebook" value={p.facebook_url}/><Field label="LinkedIn" value={p.linkedin_url}/><Field label="X" value={p.x_url}/><Field label="Contact" value={p.contact_person_name}/><Field label="Role" value={p.contact_person_role}/><Field label="Source confidence" value={`${p.source_confidence}%`}/><Field label="Data confidence" value={`${p.data_confidence}%`}/></dl>
   <div className="qf-aarohi-panel-head" style={{marginTop:18}}><div><h2>Sources</h2><p>Observed provenance</p></div></div>{data.sources.length?data.sources.slice(0,8).map((s:any)=><div className="qf-aarohi-note" key={s.id} style={{marginBottom:6}}><b>{s.source_type}</b> · {s.source_name||"Source"}<br/><small>{s.source_url||s.raw_business_name||"No public URL"} · confidence {s.confidence}%</small></div>):<p className="qf-aarohi-note">No source records.</p>}
   <div className="qf-aarohi-panel-head" style={{marginTop:18}}><div><h2>Channel identities</h2></div></div>{data.channels.map((c:any)=><div key={c.id} className="qf-aarohi-note" style={{marginBottom:5}}><b>{c.channel}</b> · {c.display_name||c.external_reference} <AarohiBadge>{c.verification_status}</AarohiBadge></div>)}
  </aside>
  <main className="qf-aarohi-panel"><div className="qf-aarohi-panel-head"><div><h2>Unified timeline</h2><p>Append-only acquisition events across merged identities.</p></div></div><div className="qf-aarohi-timeline">{data.events.length?data.events.map((e:any)=><article className="qf-aarohi-event" key={e.id}><b>{e.event_type}</b><p>{e.safe_summary||"Structured event"}</p><small>{formatWhen(e.occurred_at)} · {e.actor_type}{e.channel?` · ${e.channel}`:""}{e.reference_type?` · ${e.reference_type}`:""}</small></article>):<p className="qf-aarohi-note">No events yet.</p>}</div>
   <div className="qf-aarohi-panel-head" style={{marginTop:16}}><div><h2>Conversion</h2><p>Package/payment/activation facts are never manually asserted here.</p></div></div><div className="qf-aarohi-conversion"><div className="qf-aarohi-convrow"><span>Registration projection</span><b>{p.registration_stage}</b></div><div className="qf-aarohi-convrow"><span>Commercial projection</span><b>{p.commercial_stage}</b></div><div className="qf-aarohi-convrow"><span>Payment projection</span><b>{p.payment_stage}</b></div><div className="qf-aarohi-convrow"><span>Core activation</span><b>{handoff?"Confirmed":"Waiting on Core"}</b></div>{handoff?<div className="qf-aarohi-note"><b>AAROHI ACQUISITION COMPLETE</b><br/>Transferred to Anisha / Vendor CRM · <Link href={`/admin/vendor-crm/vendors/${handoff.vendor_id}`}>Open Vendor CRM ↗</Link></div>:null}</div>
   {data.opportunities.length?<div className="qf-aarohi-note" style={{marginTop:10}}>Interested package: <b>{(data.opportunities[0] as any).packages?.name||"Canonical package"}</b>. Display price ₹{(data.opportunities[0] as any).packages?.display_price??"—"} is read from Core.</div>:null}
   {core?<div className="qf-aarohi-note" style={{marginTop:10}}>Core vendor: <b>{core.vendor?.business_name}</b> · {core.vendor?.status} · payment records {core.payments.length} · package records {core.vendorPackages.length}</div>:null}
  </main>
  <aside className="qf-aarohi-panel qf-aarohi-intelligence"><div className="qf-aarohi-panel-head"><div><h2>AAROHI</h2><p>Acquisition intelligence & operator control</p></div><AarohiBadge tone={p.human_takeover?"hot":p.ai_paused?"warn":"good"}>{p.human_takeover?"HUMAN":p.ai_paused?"PAUSED":"ACTIVE"}</AarohiBadge></div>
   <div className="qf-aarohi-scoregrid"><div className="qf-aarohi-score"><span>Qualification</span><b>{score.qualification_score??0}</b></div><div className="qf-aarohi-score"><span>Contactability</span><b>{score.contactability_score??0}</b></div><div className="qf-aarohi-score"><span>Engagement</span><b>{score.engagement_score??0}</b></div><div className="qf-aarohi-score"><span>Commercial intent</span><b>{score.commercial_intent_score??0}</b></div><div className="qf-aarohi-score"><span>Data confidence</span><b>{score.data_confidence_score??p.data_confidence}</b></div><div className="qf-aarohi-score"><span>Priority</span><b>{p.priority_band}</b></div></div>
   <dl className="qf-aarohi-profile-list"><Field label="Journey" value={p.prospect_stage}/><Field label="Conversation" value={p.conversation_stage}/><Field label="Objection" value={p.current_objection}/><Field label="Preferred" value={p.preferred_channel}/><Field label="Next action" value={p.next_action_type}/><Field label="Follow-up" value={formatWhen(p.next_action_at)}/><Field label="Summary" value={p.conversation_summary}/><Field label="Risks" value={p.risks_blockers}/></dl>
   <div className="qf-aarohi-actions"><form action={takeoverProspectAction.bind(null,p.id,!p.human_takeover)}><button className="qf-aarohi-btn" data-tone={p.human_takeover?"ghost":"primary"}>{p.human_takeover?"Release human":"Take over"}</button></form><form action={pauseAarohiAction.bind(null,p.id,!p.ai_paused)}><button className="qf-aarohi-btn" data-tone="ghost">{p.ai_paused?"Resume Aarohi":"Pause Aarohi"}</button></form></div>
   <details style={{marginTop:10}}><summary className="qf-aarohi-btn" data-tone="ghost">Update workflow</summary><form action={updateWorkflowAction.bind(null,p.id)} className="qf-aarohi-formgrid" style={{marginTop:8}}><label>Prospect stage<select name="prospect_stage" className="qf-aarohi-select" defaultValue={p.prospect_stage}>{["DISCOVERED","ENRICHED","QUALIFIED","OUTREACH_READY","CONTACTED","ENGAGED","INTERESTED","CONVERSION","LOST"].map(x=><option key={x}>{x}</option>)}</select></label><label>Conversation<select name="conversation_stage" className="qf-aarohi-select" defaultValue={p.conversation_stage}>{["NONE","FIRST_CONTACT","REPLIED","DISCOVERY","OBJECTION","PITCH","WHATSAPP_HANDOFF","FOLLOW_UP","CLOSING"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select name="priority_band" className="qf-aarohi-select" defaultValue={p.priority_band}>{["A+","A","B","C","D"].map(x=><option key={x}>{x}</option>)}</select></label><label>Preferred<input name="preferred_channel" className="qf-aarohi-input" defaultValue={p.preferred_channel||""}/></label><label>Next action<input name="next_action_type" className="qf-aarohi-input" defaultValue={p.next_action_type||""}/></label><label>Due<input name="next_action_at" type="datetime-local" className="qf-aarohi-input"/></label><label className="wide">Reason<input name="next_action_reason" className="qf-aarohi-input" defaultValue={p.next_action_reason||""}/></label><label className="wide">Objection<input name="current_objection" className="qf-aarohi-input" defaultValue={p.current_objection||""}/></label><button className="qf-aarohi-btn" data-tone="primary">Save local workflow</button></form></details>
   <details style={{marginTop:10}}><summary className="qf-aarohi-btn" data-tone="ghost">Add task / follow-up</summary><form action={createTaskAction.bind(null,p.id)} className="qf-aarohi-formgrid" style={{marginTop:8}}><label>Task type<select name="task_type" className="qf-aarohi-select">{["CALL","FOLLOW_UP","WHATSAPP","REVIEW","IDENTITY_REVIEW","REGISTRATION_ASSIST","PAYMENT_FOLLOWUP","HUMAN_CALLBACK","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select name="priority" className="qf-aarohi-select"><option>HIGH</option><option selected>NORMAL</option><option>LOW</option></select></label><label>Due<input name="due_at" type="datetime-local" className="qf-aarohi-input"/></label><label className="wide">Reason<input name="reason" className="qf-aarohi-input" required/></label><button className="qf-aarohi-btn" data-tone="primary">Create task</button></form></details>
   <details style={{marginTop:10}}><summary className="qf-aarohi-btn" data-tone="ghost">Update structured scoring</summary><form action={scoreProspectAction.bind(null,p.id)} className="qf-aarohi-formgrid" style={{marginTop:8}}>{[["qualification_score","Qualification"],["contactability_score","Contactability"],["engagement_score","Engagement"],["commercial_intent_score","Commercial intent"],["data_confidence_score","Data confidence"]].map(([name,label])=><label key={name}>{label}<input name={name} type="number" min="0" max="100" className="qf-aarohi-input" defaultValue={(score as any)[name]??0}/></label>)}<label className="wide">Reason codes<input name="score_reason_codes" className="qf-aarohi-input" placeholder="PHONE_AVAILABLE"/></label><button className="qf-aarohi-btn" data-tone="primary">Save score</button></form></details>
   <details style={{marginTop:10}}><summary className="qf-aarohi-btn" data-tone="ghost">Package interest</summary><div className="qf-aarohi-stack" style={{marginTop:8}}>{packages.map((pack:any)=><form key={pack.id} action={selectPackageAction.bind(null,p.id,pack.id)} className="qf-aarohi-package-row"><div><b>{pack.name}</b><small>₹{pack.display_price} · {pack.lead_count} leads · {pack.validity_days} days</small></div><button className="qf-aarohi-btn" data-tone="ghost">Select</button></form>)}</div></details>
   <details style={{marginTop:10}}><summary className="qf-aarohi-btn" data-tone="danger">Do not contact</summary><form action={suppressProspectAction.bind(null,p.id)} className="qf-aarohi-formgrid" style={{marginTop:8}}><label className="wide">Governed suppression reason<input name="reason" required className="qf-aarohi-input"/></label><button className="qf-aarohi-btn" data-tone="danger">Suppress prospect</button></form></details>
   {data.matches.length?<div style={{marginTop:14}}><div className="qf-aarohi-panel-head"><div><h2>Identity review</h2><p>No silent auto-merge.</p></div></div>{data.matches.map((m:any)=><div className="qf-aarohi-note" key={m.id} style={{marginBottom:7}}><b>Possible duplicate · {m.match_score}%</b><br/><small>{m.status} · phone {m.phone_match?"yes":"no"} · domain {m.domain_match?"yes":"no"} · name {m.name_match?"yes":"no"}</small>{m.status==="RECOMMENDED"?<div className="qf-aarohi-actions"><form action={identityDecisionAction.bind(null,m.id,p.id,"CONFIRMED")}><button className="qf-aarohi-btn" data-tone="ghost">Confirm merge into this record</button></form><form action={identityDecisionAction.bind(null,m.id,undefined,"REJECTED")}><button className="qf-aarohi-btn" data-tone="ghost">Reject</button></form></div>:null}</div>)}</div>:null}
   {!handoff?<details style={{marginTop:10}}><summary className="qf-aarohi-btn" data-tone="ghost">Core handoff</summary><form action={completeHandoffAction.bind(null,p.id)} className="qf-aarohi-formgrid" style={{marginTop:8}}><label className="wide">Canonical vendor ID<input name="vendor_id" required className="qf-aarohi-input" placeholder="Validated against Core activation authority"/></label><p className="qf-aarohi-danger-note wide">This cannot create or activate a vendor. It succeeds only when the canonical vendor already satisfies QuickFurno activation facts.</p><button className="qf-aarohi-btn" data-tone="primary">Validate & complete handoff</button></form></details>:null}
  </aside>
 </div>
 </>}
