import Link from "next/link";
import { AarohiMetric,AarohiPageHead,AarohiBadge } from "@/components/admin/aarohi/AarohiPrimitives";
import { getAarohiOverview } from "@/services/aarohiCrmService";
export const dynamic="force-dynamic";
export default async function AarohiOverviewPage({searchParams}:{searchParams?:Record<string,string|string[]|undefined>}){
 const raw=Array.isArray(searchParams?.period)?searchParams?.period[0]:searchParams?.period;const days=raw==="30"?30:raw==="1"?1:7;const data=await getAarohiOverview(days);const max=Math.max(1,...data.funnel.map(x=>x.count));
 return <><AarohiPageHead title="Acquisition overview" description="Prospect discovery through authoritative Core activation. Vendor CRM begins only after handoff." action={<div className="qf-aarohi-filters"><Link className="qf-aarohi-btn" data-tone="ghost" href="?period=1">Today</Link><Link className="qf-aarohi-btn" data-tone="ghost" href="?period=7">7 Days</Link><Link className="qf-aarohi-btn" data-tone="ghost" href="?period=30">30 Days</Link></div>}/>
 <div className="qf-aarohi-metrics"><AarohiMetric label="New prospects" value={data.kpis.newProspects}/><AarohiMetric label="Qualified" value={data.kpis.qualified}/><AarohiMetric label="Outreach ready" value={data.kpis.outreachReady}/><AarohiMetric label="Follow-ups due" value={data.kpis.followupsDue}/><AarohiMetric label="Active conversations" value={data.kpis.activeConversations}/><AarohiMetric label="Interested" value={data.kpis.interested}/><AarohiMetric label="Activated" value={data.kpis.activated}/><AarohiMetric label="Handoffs" value={data.kpis.handoffs}/></div>
 <div className="qf-aarohi-grid2"><section className="qf-aarohi-panel"><div className="qf-aarohi-panel-head"><div><h2>Acquisition funnel</h2><p>Local CRM stages; payment and activation remain Core facts.</p></div></div><div className="qf-aarohi-funnel">{data.funnel.map((row,i)=>{const prev=i?data.funnel[i-1].count:null;const rate=prev?Math.round(row.count/prev*100):null;return <div className="qf-aarohi-funnel-row" key={row.stage}><span>{row.stage}</span><div className="qf-aarohi-funnel-track"><div className="qf-aarohi-funnel-fill" style={{width:`${Math.max(2,row.count/max*100)}%`}}/></div><b>{row.count}{rate!==null?<small> · {rate}%</small>:null}</b></div>})}</div></section>
 <section className="qf-aarohi-panel"><div className="qf-aarohi-panel-head"><div><h2>Aarohi attention required</h2><p>Operator queue, not a provider inbox.</p></div><Link href="/admin/aarohi/inbox">Open inbox</Link></div><div className="qf-aarohi-attention">{data.attention.length?data.attention.map((x:any)=><Link key={x.id} href={`/admin/aarohi/prospects/${x.id}`}><div><b>{x.business_name}</b><small>{x.attention_reason}</small></div><AarohiBadge tone={x.priority_band==="A+"?"hot":"warn"}>{x.priority_band}</AarohiBadge></Link>):<p className="qf-aarohi-note">No acquisition items currently need intervention.</p>}</div></section></div></>;
}
