import { AarohiBadge,AarohiPageHead,ProspectLink,formatWhen } from "@/components/admin/aarohi/AarohiPrimitives";
import { listAarohiProspects } from "@/services/aarohiCrmService";
export const dynamic="force-dynamic";
const cols=[
 ["NEW",["DISCOVERED"]],["ENRICHED",["ENRICHED"]],["QUALIFIED",["QUALIFIED"]],["OUTREACH",["OUTREACH_READY","CONTACTED"]],
 ["REPLIED",["ENGAGED"]],["INTERESTED",["INTERESTED"]],["WHATSAPP",["INTERESTED"]],["REGISTRATION",["CONVERSION"]],["PACKAGE",["CONVERSION"]],["PAYMENT",["CONVERSION"]],["ACTIVATION",["CONVERSION"]],["WON",["WON"]],
] as const;
export default async function PipelinePage(){const data=await listAarohiProspects({page:1});const rows:any[]=data.rows as any[];return <><AarohiPageHead title="Acquisition pipeline" description="Kanban is a CRM projection only. Payment and activation cannot be advanced by drag-and-drop; authoritative states remain read-only."/>
<div className="qf-aarohi-kanban">{cols.map(([name,stages])=>{const items=rows.filter((r:any)=>stages.includes(r.prospect_stage as never));return <section className="qf-aarohi-kanban-col" key={name}><div className="qf-aarohi-kanban-head"><span>{name}</span><b>{items.length}</b></div>{items.map((r:any)=><article className="qf-aarohi-card" key={r.id}><h3><ProspectLink id={r.id}>{r.business_name}</ProspectLink></h3><p>{r.area||r.cities?.name||"Pune"} · {r.primary_category||"Uncategorised"}</p><div className="qf-aarohi-cardmeta"><AarohiBadge tone={r.priority_band==="A+"?"hot":"neutral"}>{r.priority_band}</AarohiBadge>{r.whatsapp_available?<AarohiBadge tone="good">WhatsApp ✓</AarohiBadge>:null}{r.website?<AarohiBadge>Website ✓</AarohiBadge>:null}{r.instagram_url?<AarohiBadge>Instagram ✓</AarohiBadge>:null}</div><small>Last {formatWhen(r.last_activity_at)}<br/>Next {r.next_action_type||"—"}{r.next_action_at?` · ${formatWhen(r.next_action_at)}`:""}</small></article>)}</section>})}</div>
<div className="qf-aarohi-table-wrap"><table className="qf-aarohi-table"><thead><tr><th>Business</th><th>Prospect stage</th><th>Conversation</th><th>Priority</th><th>Next action</th><th>Owner</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><ProspectLink id={r.id}>{r.business_name}</ProspectLink></td><td>{r.prospect_stage}</td><td>{r.conversation_stage}</td><td>{r.priority_band}</td><td>{r.next_action_type||"—"}</td><td>{r.human_takeover?"HUMAN":r.agent_owner}</td></tr>)}</tbody></table></div></>}
